name: Cake Pipeline

on:
    push:
        branches:
            - cake-setup
            - develop
            - master

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run Script
              uses: actions/run-windows@v1
              with:
                  args: pwsh -Command ".\build.ps1"
